#!/bin/bash

PKG=$1
REL=$2
DIR=$3
DESC=$4
TIMESTAMP=$(date '+%a, %d %b %Y %T -0000' --utc)

DEST=$DIR/debian/changelog
if [ ! "$DESC" ]; then
	DESC=$(basename $DIR)
fi

if [ ! -e $DEST ]; then
	echo $DEST does not exist
	exit 1
fi

echo -e "$PKG ($REL) unstable; urgency=medium\n\n  * Autogenerated from $(basename $DIR)\n\n -- Autobuild <xrobau@gmail.com>  $TIMESTAMP" > $DEST

